<?php

$title = "Delete Prize Wheel for Page ID ".$this->prizewheel->pageId();
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title)?></h2>

<form action="<?php echo $this->url('prize-wheel', array('action' => 'disable', 'id' => $this->prizewheel->id()))?>" method="post">
	<p>Do you really want to remove this Prize Wheel? Please note you will also need to uninstall the App from your Facebook Page.</p>
	<button type="submit" name="del" value="yes">
		Yes
	</button>
	<button type="submit" name="del" value="no">
		No
	</button>
</form>