<?php
$this->layout($this->layoutpath);
$title = "Manage Prize Wheel " . $this->prizewheel->id();
$this->headTitle($title);

$form = $this->form;
$form->setAttribute("action", $this->url("prize-wheel", array("action" => "manage", "id" => $this->prizewheel->id())));
$form->prepare();
?>
<h2>Manage Prize Wheel for Facebook Page <?php echo $this->escapeHtml($this->facebookpage)?></h2>
<?php echo $this->form()->openTag($form)?>
<table>
	<tr>
		<td>
			<?php echo $this->formRow($form->get('categories'))?>
		</td>
	</tr>
	<?php if($this->isadmin):?>
	<tr>
		<td>
			<?php echo $this->formRow($form->get('enabled'))?>
		</td>
	</tr>
	<?php endif;?>
	<tr>
		<td>
			<button id="save-changes" type="submit">
				Save
			</button>
			<button id="cancel-changes" type="button">
				Cancel
			</button>
		</td>
	</tr>
</table>
<?php echo $this->form()->closeTag()?>
<script type="text/javascript">
	$(document).ready(function(){

		$("#cancel-changes").click(function(){
			window.location = '<?php echo $this->isadmin ? '/prize-wheel/list' : '/affiliate'?>';
		});
	});
</script>