<?php

$this->layout($this->layoutpath);
$title = "Affiliate Payout Entries";
$this->headTitle($title);
?>
<script type="text/javascript" src="/js/jquery.simplePagination.js"></script>
<link type="text/css" href="/css/simplePagination.css" rel="stylesheet" />

<?php if(!$this->isadmin):?>
<div>
	<a href="<?php echo $this->url('affiliate')?>">Return to Affiliate Dashboard</a>
</div>
<?php endif;?>

<h2><?php echo $this->escapeHtml($title)?> - <?php echo $this->escapeHtml($this->count)?></h2>

<div id="paginator"></div>

<table>
	<thead>
		<tr>
			<th style="text-align: left;">ID</th>
			<th style="text-align: left;">Affiliate</th>
			<th style="text-align: left;">Amount</th>
			<th style="text-align: left;">Method</th>
			<th style="text-align: left;">Status</th>
			<th style="text-align: left;">Transaction ID</th>
			<th style="text-align: left;">Created</th>	
		</tr>
	</thead>
	<tbody id="list-body">
		<?php foreach($this->affiliatepayoutentries as $affiliatePayoutEntry):?>
		<tr>
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->id())?></td>
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->affiliateName())?></td>
			<td><?php echo $this->escapeHtml(number_format($affiliatePayoutEntry->amount(), 2, '.', ','))?></td>
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->payoutMethod())?></td>	
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->claimedStatus())?></td>
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->transactionId())?></td>
			<td><?php echo $this->escapeHtml($affiliatePayoutEntry->createDateTime())?></td>
		</tr>
		<?php endforeach;?>
		
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$("#paginator").pagination({
			items: <?php echo $this->count?>,
			itemsOnPage: 25,
			cssStyle: 'light-theme',
			onPageClick: function(pageNumber){
				$.ajax({
					url: '<?php echo $this->url('affiliate-payout-entry', array('action' => 'list'))?>',
					type: 'post',
					data: 'page=' + pageNumber,
					dataType: 'json',
					success: function(response){

						var listBody = $("#list-body");
						
						listBody.empty();

						$.each(response.affiliatepayoutentries, function(index, affiliatepayoutentry){
			
							var row = $('<tr></tr>');
						
							row.append($('<td>' + affiliatepayoutentry.id + '</td>'));							
							row.append($('<td>' + affiliatepayoutentry.affiliatename + '</td>'));
							row.append($('<td>' + parseFloat(affiliatepayoutentry.amount).toFixed(2) + '</td>'));
							row.append($('<td>' + affiliatepayoutentry.payoutmethod + '</td>'));
							row.append($('<td>' + affiliatepayoutentry.claimedstatus + '</td>'));
							row.append($('<td>' + affiliatepayoutentry.transactionid + '</td>'));
							row.append($('<td>' + affiliatepayoutentry.createdatetime + '</td>'));
							
							listBody.append(row);
						});
					}
				});
			}
		});
	});
</script>