<?php

$title = "Advertiser Dashboard";
$this->headTitle($title);
?>

<?php if(isset($this->loginredirect)):?>
<script type="text/javascript">
	window.top.location = '<?php echo $this->loginredirect?>';
</script>
<?php else:?>

<h1><?php echo $this->escapeHtml($title)?></h1>

<h1>Welcome back, <?php echo $this->escapeHtml($this->advertiser->firstName() . ' ' . $this->advertiser->lastName())?></h1>

<a href="<?php echo $this->url('advertisement', array('action' => 'create'))?>">Create Advertisement</a> |
<a href="<?php echo $this->url('transaction', array('action' => 'list', 'id' => $this->advertiser->id()))?>">My Transactions</a> |
<a href="<?php echo $this->url('advertiser', array('action' => 'manage'))?>">My Profile</a>

<table>
	<thead>
		<tr>
			<th></th>
			<th>Name</th>
			<th>Placement</th>
			<th>Type</th>
			<th>Redirect</th>
			<th>Impressions</th>
			<th>Clicks</th>
			<th>Bucket</th>
			<th>Created</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->advertisements as $advertisement):?>
		<tr>
			<td><a href="<?php echo $this->url('advertisement', array('action' => 'manage', 'id' => $advertisement->id()))?>">Manage</a></td>
			<td><?php echo $this->escapeHtml($advertisement->name())?></td>	
			<td><?php echo $this->escapeHtml($advertisement->placementTypeName())?></td>		
			<td><?php echo $this->escapeHtml($advertisement->typeName())?></td>
			<td><?php echo $this->escapeHtml($advertisement->url())?></td>
			<td><?php echo $this->escapeHtml($advertisement->impressions())?></td>
			<td><?php echo $this->escapeHtml($advertisement->clicks())?></td>
			<td><?php echo $this->escapeHtml($advertisement->bucket())?></td>
			<th><?php echo $this->escapeHtml($advertisement->createDateTime())?></th>
			<td><a href="<?php echo $this->url('advertisement', array('action' => 'disable', 'id' => $advertisement->id()))?>">Remove</a></td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){

		$("#create-new-advertisement-btn").click(function(){
			window.location = '<?php echo $this->url("advertisement", array("action" => "create")) ?>';
		});
	});
</script>
<?php endif;?>