<?php

$title = "Create a new Advertisement";
$this->headTitle($title);

$form = $this->createform;
$form->setAttribute("action", $this->url("advertisement", array("action" => "create")));
$form->prepare();
?>
<h2><?php echo $this->escapeHtml($title)?></h2>

<?php echo $this->form()->openTag($form)?>
<table>
	<tr>
		<td>
			<?php echo $this->formRow($form->get("name"))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get("description"))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get('url'))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get("typeid"))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get("advertisementplacementtypeid"))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get('categories'))?>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->formRow($form->get("bannerimage"))?>
		</td>
	</tr>
	<tr>
		<td>
			<button type="submit" id="create-advertisement-btn">
				Create
			</button>
		</td>
	</tr>
</table>
<?php echo $this->form()->closeTag()?>
<script type="text/javascript">
	$(document).ready(function(){

		$("#<?php echo $form->getName()?>").validate({
			rules: {
				name : {
					required : true
				}
			},
			messages : {
				name : {
					required : "Please provide a Name for your Advertisement."
				}
			}
		});
	});
</script>