<?php

$title = "Affiliate Dashboard";
$this->headTitle($title);
?>

<?php if(isset($this->loginredirect)):?>
<script type="text/javascript">
	window.top.location = '<?php echo $this->loginredirect?>';
</script>
<?php else:?>

This is the <?php echo $this->escapeHtml($title)?>
<br/>

<h1>Welcome back, <?php echo ($affiliate->firstName() . " " . $affiliate->lastName())?></h1>

<button id="install-prize-wheel-btn">Install Prize Wheel</button>

<table>
	<tr>
		<td>
			<h2>Your Prize Wheel Installations</h2>
			<table id="prize-wheel-installation-table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
						<th>Page</th>
						<th>Type</th>
						<th>Views</th>
						<th>Plays</th>
						<th>Banner Clicks</th>
						<th>Revenue</th>
						<th>Installed</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->prizewheels as $prizeWheel):?>
					<tr>
						<td><a href="#">View</a></td>
						<td><a href="#">Stats</a></td>
						<td><a href="/prize-wheel/manage/<?php echo $this->escapeHtml($prizeWheel->id())?>">Manage</a></td>
						<td><a href="#" target="_blank" id="fb-prizewheel-pageid-<?php echo $this->escapeHtml($prizeWheel->id())?>"><?php echo $this->escapeHtml($prizeWheel->pageId())?></a></td>
						<td><?php echo $this->escapeHtml($prizeWheel->prizeWheelTypeName())?></td>
						<td><?php echo $this->escapeHtml($prizeWheel->views())?></td>
						<td><?php echo $this->escapeHtml($prizeWheel->plays())?></td>
						<td><?php echo $this->escapeHtml($prizeWheel->advertisementClicks())?></td>
						<td><?php echo $this->escapeHtml('$'.number_format($prizeWheel->advertisementClicks() * 0.05, 2, '.', ','))?></td>
						<td><?php echo $this->escapeHtml($prizeWheel->createDateTime())?></td>
						<td><a href="<?php echo $this->url('prize-wheel', array('action' => 'disable', 'id' => $this->escapeHtml($prizeWheel->id())))?>">Remove</a></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</td>
	</tr>
</table>

<div id="install-prizewheel-dialog">
	<label for="fb-page">Install Prize Wheel to Page</label>
	<select id="fb-page" name="fb-page"></select>
	<label for="prizewheeltypeid">Prize Wheel Type</label>
	<select id="prizewheeltypeid" name="prizewheeltypeid">
		<?php foreach($this->prizewheeltypes as $prizeWheelType):?>
		<option value="<?php echo $prizeWheelType->id()?>"><?php echo $prizeWheelType->name()?></option>
		<?php endforeach;?>
	</select>
	<select multiple="multiple" id="prizewheel-categories" name="prizewheel-categories">
		<?php foreach($this->categories as $category):?>
		<option value="<?php echo $category->id()?>"><?php echo $category->name()?></option>
		<?php endforeach?>
	</select>
	<button id="add-prizewheel-to-page">
		Install!
	</button>
</div>

<script type="text/javascript">
	$(document).ready(function(){

		$("#install-prizewheel-dialog").dialog({
			title: "Install the Prize Wheel",
			width: 300,
			height: 325,
			autoOpen: false,
			modal: true
		});

		$("#prize-wheel-installation-table a[id^='fb-prizewheel-pageid-']").each(function(){
			$(this).attr("href", "https://facebook.com/" + $(this).html());
		});

		$("#install-prize-wheel-btn").click(function(){
			$("#install-prizewheel-dialog").dialog("open");
		});

		$("#add-prizewheel-to-page").click(function(){			
			
			var categories = $("#prizewheel-categories");	
			
			var fbPageId = $("#fb-page").val();
			
			$.ajax({
				url: '<?php echo $this->url('prize-wheel', array('action' => 'installer'))?>',
				data: {
					prizewheeltypeid: $("#prizewheeltypeid").val(),
					pageid: fbPageId,
					categories: categories.val().join('|')
				},
				type: 'post',
				dataType : "json",
				success: function(response){
					if(response.status == "success"){
						// Install the App on Facebook.
						FB.api("/" + fbPageId + "/?fields=access_token", function(response){
							FB.api("/" + fbPageId + "/tabs", "post", { app_id: appId, access_token: response.access_token }, function(response){
								fetchPages();
								$("#install-prizewheel-dialog").dialog("close");
								window.location = '<?php echo $this->url('affiliate')?>';
							});
						});
					} // if
					else{
						alert(response.status);
						// elegantly notify the affiliate of the error.
					} // 
				}
			});
		});
	});

	var appId = '<?php echo $this->fbappid?>';

	window.fbAsyncInit = function(){

		FB.init({
			appId: appId,
			cookie: true,
			status: true,
			channelUrl: '//fbstaging.ecrmplus.net:9090/channel.html',
			oauth: true,
			xfbml: true
		});

		FB.login(function(response){
			if(response.status == "connected"){
				fetchPages();
			} // if
			else{
				FB.login(function(response){
					if(response.status == "connected"){
						fetchPages();
					} // if
					else{
						window.top.location = '/';
					} // else
				}, {scope: 'email, manage_pages'});
			}
		});
		
		FB.getLoginStatus(function(response){
		
			if(response.status == "connected"){
				fetchPages();
			} // if
			else{
				FB.login(function(response){
					if(response.status == "connected"){
						fetchPages();
					} // if
					else{
						window.top.location = '/';
					} // else
				}, {scope: 'email, manage_pages'});
			}
		}, true);
	};

	function fetchPages(){
		var fbpages = $("#fb-page");
		fbpages.children().remove();

		FB.api('/me/accounts', function(response){							

			var length = response.data.length;
			var count = 1;

			$.each(response.data, function(idx, page){										

				var found = false;				
					
				FB.api('/' + page.id + '/tabs', function(response, pageCount){
					
					$.each(response.data, function(idx, tab){
						if(tab.application !== undefined){
							if(tab.application.id == appId){
								found = true;								
							} //
						} // if					
					});

					if(!found){
						fbpages.append($('<option value="' + page.id + '">' + page.name + '</option>'));				
					} // if

					count++;

					if(count == length && fbpages.children().length <= 0){						
						
					} // if												
				});													
			});							
		});	
	}

	(function(){
		var e = document.createElement('script');
		e.type = "text/javascript";
		e.src = document.location.protocol + "//connect.facebook.net/en_US/all.js";
		e.async = true;
		document.getElementById("fb-root").appendChild(e);
	}());
</script>
<?php endif;?>