<div>
	<div>
		Big Image of the PrizeWheel with text like: <br/>
		Welcome to the FB PrizeWheel. Add the App to your Page today to earn Advertisement revenue. Become an Advertisor today to have your banner
		displayed on all of our customer's Prize Wheel enabled pages.
		<br/>
	</div>
	<br/>
	<div style="width: 500px; height: 125px;">
		<div style="width: 150px; height: 100px; border-style: solid; border-width: 1px; float: left;">
			Install the Prize-Wheel
		</div>
	
		<div style="width: 150px; height: 100px; border-style: solid; border-width: 1px; float: right;">
			Become an Affiliate
		</div>
	</div>
</div>
